AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Description: API resources

Resources:

# Serverless setup: Lambda function + HTTP API

  BranchHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Description: branch-project-1985-api
      DefaultRouteSettings:
        DetailedMetricsEnabled: false
        DataTraceEnabled: false
        ThrottlingBurstLimit: 3
        ThrottlingRateLimit: 1
      Tags:
        NameTag: branch-project-1985

  BranchHttpApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: branch-project-1985-function
      Description: branch-project-1985-function
      Handler: app.main.lambda_handler
      CodeUri: s3://branch-project-1985-storage/branch-project-1985-api.zip
      PackageType: Zip
      Role: !Join [":", ["arn:aws:iam:", !Ref AWS::AccountId, "role/branch-project-1985-role"]]
      MemorySize: 256
      Timeout: 10
      Runtime: python3.9
      ReservedConcurrentExecutions: 3
      Environment:
        Variables:
          ENV_NAME: dev
          LOG_LEVEL: INFO
          SECRET_KEY: yCWSozCORtMq_vHSAjkHPFtJuZd50Fb26rzTY7uK1BiwhRgpBaNnWpJeYNLZxfUYCdOPSXQiLomBsrQtp36Fwh
          API_GATEWAY_URL_BRANCH: branch-project-1985
          INSTANTIATE_LAMBDA_HANDLER_ON_IMPORT: true
      Events:
        HttpApiEventGet:
          Type: HttpApi
          Properties:
            Method: GET
            Path: "/{proxy+}"
            ApiId:
              Ref: BranchHttpApi
        HttpApiEventPut:
          Type: HttpApi
          Properties:
            Method: PUT
            Path: "/{proxy+}"
            ApiId:
              Ref: BranchHttpApi
        HttpApiEventPost:
          Type: HttpApi
          Properties:
            Method: POST
            Path: "/{proxy+}"
            ApiId:
              Ref: BranchHttpApi
      Tags:
        NameTag: branch-project-1985
